version: '2'
services:

     redis:
        image: redis
        ports:
        - "6379:6379"
        networks:
        - api
     redis:
        image: ramymn/demoapi
        ports:
        - "5000:5000"
        networks:
        -api
        environment:
        - redis_ip: redis
        - redis_port: 6379
networks:
    api:
        driver: bridge